name: voice_remind
description: A beautiful voice-first reminder application
version: 1.1.5+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.8

  # Simple Local Storage - No Hive for now, just SharedPreferences
  shared_preferences: ^2.3.3

  # Date & Time Utilities
  intl: ^0.19.0

  # Notifications (latest version)
  flutter_local_notifications: ^18.0.1
  # Slidable for swipe actions
  flutter_slidable: ^3.1.1
  timezone: ^0.10.1

  # Utils
  uuid: ^4.5.1

  # AI and HTTP Requests
  google_generative_ai: ^0.4.6
  http: ^1.1.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.2.4    
  
  # Secrets and Environment Variables
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0
  permission_handler: ^12.0.1
  device_info_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  # Assets (for future use)
  assets:
  - .env
  #   - images/
  #   - sounds/

  # Custom fonts (for future use)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf